name: Build-APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Sistem Araclarini Yukle
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython

      - name: APK Derle (Nova Govdesi)
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug || true

      - name: APK Dosyasini Hazirla
        uses: actions/upload-artifact@v4
        with:
          name: Nova-Uygulamasi
          path: bin/*.apk
